# Generated by Django 6.0.2 on 2026-02-12 14:19

import django.db.models.deletion
import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='papers/', validators=[papers.models.validate_pdf])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.subject')),
            ],
        ),
    ]
