# Generated by Django 6.0.2 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='class_name',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
