# Generated by Django 6.0.2 on 2026-03-08 13:41

import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visitor Count',
            },
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='pdf',
            field=models.FileField(storage=papers.models.get_supabase_storage, upload_to='question_papers/'),
        ),
    ]
