# Generated by Django 6.0.2 on 2026-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th')], max_length=10),
        ),
    ]
